version: '3.8'

services:
  payment-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-gateway
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/dev.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - payment-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - payment-gateway
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge

volumes:
  data:
  logs:
